---
# Source: rhsso-operator-chart/templates/operator-group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.metadata.name }}-operator-operator-group
  namespace: {{ .Values.metadata.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.metadata.namespace }}
