---
# Source: rhsso-operator-chart/templates/operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    operators.coreos.com/service-registry-operator.openshift-operators: ''
spec:
  channel: {{ .Values.spec.channel }}
  installPlanApproval: {{ .Values.spec.installPlanApproval }}
  name: {{ .Values.spec.name }}
  source: {{ .Values.spec.source }}
  sourceNamespace: {{ .Values.spec.sourceNamespace }}
  startingCSV: {{ .Values.spec.startingCSV }}