---
# Source: rhsso-operator-chart/templates/operator-group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.metadata.name }}-operator-operator-group
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    olm.providedAPIs: MicrocksInstall.v1alpha1.microcks.github.io
spec:
  targetNamespaces:
  - {{ .Values.metadata.namespace }}
