apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: 3scale-apimanager
  namespace: 3scale
  uid: api-manager-3scale
spec:
  wildcardDomain: apps.cluster-qxhp4.qxhp4.sandbox2918.opentlc.com
